import { Geist, Geist_Mono } from "next/font/google";

import { ReactQueryProvider } from "@/components/providers/QueryClientProvider";

import { DictionaryProvider } from "@/components/providers/DictionaryProvider";
import ThemeProvider from "@/components/providers/ThemeProvider";
import { getTheme } from "@/core/utils/getTheme";
import "@/styles/globals.css";
import { getDictionary } from "get-dictionary";
import { ToastContainer } from "react-toastify";
import { DICTIONARY_PATH } from "../core/consts";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function Root(props: { children: React.ReactNode }) {
	const dictionary = await getDictionary(DICTIONARY_PATH.HEADER);

	const { isDarkMode } = await getTheme();

	const { children } = props;

	const theme = isDarkMode ? "dark" : "light";

	return (
		<html
			lang="en"
			suppressHydrationWarning
			className={isDarkMode ? "dark" : ""}
		>
			<body
				className={`${geistSans.variable} ${geistMono.variable} dark:bg-dark-900 bg-slate-50 text-slate-900 antialiased dark:text-white`}
			>
				<ReactQueryProvider>
					<ThemeProvider initialTheme={theme}>
						<DictionaryProvider dictionary={dictionary}>
							{children}
							<ToastContainer theme={theme} />
						</DictionaryProvider>
					</ThemeProvider>
				</ReactQueryProvider>
			</body>
		</html>
	);
}
